CREATE TABLE mercancia (
    id_mercancia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    precio NUMBER(10,2)
);

CREATE TABLE individuo (
    id_individuo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    correo VARCHAR2(100)
);

CREATE TABLE dependiente (
    id_dependiente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    puesto VARCHAR2(50)
);

CREATE TABLE establecimiento (
    id_establecimiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    ubicacion VARCHAR2(150)
);

CREATE TABLE via_pago (
    id_via_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modalidad VARCHAR2(50)
);

CREATE TABLE operacion (
    id_operacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    id_mercancia NUMBER REFERENCES mercancia(id_mercancia),
    id_individuo NUMBER REFERENCES individuo(id_individuo),
    id_dependiente NUMBER REFERENCES dependiente(id_dependiente),
    id_establecimiento NUMBER REFERENCES establecimiento(id_establecimiento),
    id_via_pago NUMBER REFERENCES via_pago(id_via_pago),
    cantidad NUMBER,
    total NUMBER(10,2)
);


INSERT INTO individuo (nombre, correo) VALUES
('Juan Pérez', 'juan.perez@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Ana Gómez', 'ana.gomez@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Carlos Ruiz', 'carlos.ruiz@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Laura Torres', 'laura.torres@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Marta Sánchez', 'marta.sanchez@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Alberto Ramírez', 'alberto.ramirez@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Rocío Ortega', 'rocio.ortega@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Iván Castillo', 'ivan.castillo@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Lucía Vargas', 'lucia.vargas@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Pedro Jiménez', 'pedro.jimenez@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Valeria Moreno', 'valeria.moreno@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('José Mejía', 'jose.mejia@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Sofía Lozano', 'sofia.lozano@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Miguel Pardo', 'miguel.pardo@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Carmen Pina', 'carmen.pina@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Pablo Gil', 'pablo.gil@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Teresa Díaz', 'teresa.diaz@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Diego Álvarez', 'diego.alvarez@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Olga Cano', 'olga.cano@email.com');
INSERT INTO individuo (nombre, correo) VALUES
('Javier Suárez', 'javier.suarez@email.com');

-- Tiendas (establecimiento)
INSERT INTO establecimiento (nombre, ubicacion) VALUES
('Central', 'Av. Principal 101');
INSERT INTO establecimiento (nombre, ubicacion) VALUES
('Norte', 'Calle 45 #67');
INSERT INTO establecimiento (nombre, ubicacion) VALUES
('Sur', 'Carrera 23 #10');
INSERT INTO establecimiento (nombre, ubicacion) VALUES
('Este', 'Diagonal 8 #55');
INSERT INTO establecimiento (nombre, ubicacion) VALUES
('Oeste', 'Transversal 44 #32');

-- Formas de Pago (via_pago)
INSERT INTO via_pago (modalidad) VALUES ('Efectivo');
INSERT INTO via_pago (modalidad) VALUES ('Tarjeta');
INSERT INTO via_pago (modalidad) VALUES ('Transferencia');

-- Vendedores (dependiente)

INSERT INTO dependiente (nombre, puesto) VALUES ('Benjamín Ríos', 'Director de Operaciones de Ventas');
INSERT INTO dependiente (nombre, puesto) VALUES ('Cinthia López', 'Analista de Forecast');
INSERT INTO dependiente (nombre, puesto) VALUES ('Esteban Torres', 'Representante de Ventas Técnicas');
INSERT INTO dependiente (nombre, puesto) VALUES ('Gabriela Osorio', 'Asistente de Ventas');
INSERT INTO dependiente (nombre, puesto) VALUES ('Manuel Pérez', 'Jefe de Logística de Distribución');
INSERT INTO dependiente (nombre, puesto) VALUES ('Verónica Díaz', 'Consultor de Estrategia Comercial');
INSERT INTO dependiente (nombre, puesto) VALUES ('Alfonso Rivas', 'Ejecutivo de Negocios Internacionales');
INSERT INTO dependiente (nombre, puesto) VALUES ('Tania Medina', 'Asesor de Clientes VIP');
INSERT INTO dependiente (nombre, puesto) VALUES ('Julián Naranjo', 'Especialista en Capacitación de Ventas');
INSERT INTO dependiente (nombre, puesto) VALUES ('Aurora Leal', 'Gerente de Producto');
INSERT INTO dependiente (nombre, puesto) VALUES ('Osvaldo Méndez', 'Asesor de Canal Minorista');
INSERT INTO dependiente (nombre, puesto) VALUES ('Paola Jiménez', 'Supervisor de Call Center');
INSERT INTO dependiente (nombre, puesto) VALUES ('Marcos Cárdenas', 'Ejecutivo de Ventas Gubernamentales');
INSERT INTO dependiente (nombre, puesto) VALUES ('Sara Núñez', 'Asesor de Sostenibilidad');

-- Productos (mercancia)
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cepillo Dental', 'Cepillo de dientes de cerdas suaves', 1544.24);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Jabón Líquido', 'Jabón líquido antibacterial', 2021.88);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Papel Higiénico', 'Paquete de 12 rollos', 3622.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Shampoo', 'Shampoo para todo tipo de cabello', 3044.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Pasta Dental', 'Pasta con flúor', 1999.25);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Desodorante', 'En barra sin aroma', 2635.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Crema Corporal', 'Hidratante para piel seca', 4261.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Toalla Femenina', 'Paquete con 10 unidades', 2497.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Máquina de Afeitar', 'Desechable de doble filo', 1979.25);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Gel Fijador', 'Fijador de cabello mediano', 1578.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Paquete de Pilas', 'AA de larga duración', 1996.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Fósforos', 'Caja con 100 unidades', 950.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Pan Tajado', 'Paquete de 400g', 1450.10);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Leche Entera', 'Litro larga vida', 2387.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Azúcar', 'Paquete de 1 kilo', 1214.85);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Sal Fina', 'Paquete de 500g', 550.44);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Aceite Vegetal', 'Botella de 1 litro', 3626.70);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Arroz Blanco', 'Paquete de 1 kilo', 2129.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Atún en Agua', 'Lata de 170g', 1677.95);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cereal', 'Maíz hojuelas 300g', 2592.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Café Molido', 'Paquete de 250g', 3355.80);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Chocolate Instantáneo', 'Porciones solubles 200g', 3240.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Harina de Trigo', 'Paquete de 1 kilo', 1816.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Papel Aluminio', 'Rollo de 10 metros', 1087.90);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Servilletas', 'Paquete de 100 hojas', 1126.25);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Jabón en Barra', 'Empaque de 3 unidades', 688.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Detergente Líquido', 'Botella de 900ml', 1944.80);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Suavizante Textil', 'Lavado intensivo 750ml', 2207.80);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Limpiador Multiusos', 'Botella de 500ml', 1258.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Desinfectante', 'Botella de 500ml', 1991.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Escoba', 'Cerdas sintéticas', 3598.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Trapero', 'Algodón 1 unidad', 1858.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Baldes', 'Capacidad de 12 litros', 3519.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Guantes de Goma', 'Par para aseo', 1270.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Gas Butano', 'Botella portátil', 5256.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Bolsa Basura', 'Paquete de 30 unidades', 1860.10);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Esponja Multiusos', 'Paquete de 3', 1017.90);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cinta Adhesiva', 'Rollo transparente', 729.30);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Lapicero', 'Tinta azul', 599.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Lápiz', 'No. 2 escolar', 353.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cuaderno', '100 hojas rayadas', 1798.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Colores', 'Bolsa de 12 colores', 2466.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Marcador Permanente', 'Negro', 462.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Tijeras', 'De oficina pequeña', 951.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Pegante escolar', 'Tubo de 20g', 637.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Carpeta plástica', 'Oficio', 595.10);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Calculadora senc.', 'Pantalla básica', 2156.70);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Zapatilla deportiva', 'Blanca talla 39', 12888.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Camisa Polo', 'Algodón talla M', 5313.30);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Pantalón Jean', 'Azul oscuro talla 32', 17251.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Medias', 'Pack de 3 pares', 2448.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Reloj pulso', 'Análogo', 7498.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Sombrero', 'Tejido en palma', 2664.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cinturón', 'Piel sintética', 5654.70);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Bolso', 'Mediano color negro', 13101.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Mochila escolar', 'Tela resistente', 12286.75);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cargador USB', 'Doble salida', 3595.80);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Audífonos', 'Cableados básicos', 4942.75);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Lámpara LED', 'Con pilas recargables', 6247.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Regleta eléctrica', '4 tomas', 2565.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Mouse óptico', 'USB', 2105.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Teclado', 'Membrana USB', 4558.30);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Libreta de notas', 'Pequeña a5', 1117.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Agua embotellada', 'Botella 1.5 litros', 708.70);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Gaseosa', 'Botella de 2 litros', 1691.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Jugo natural', 'Botella de 1 litro', 1557.70);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Bebida energética', 'Lata de 250ml', 1909.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Galletas saladas', 'Paquete 6 unidades', 957.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Pan de molde', 'Paquete 24 rebanadas', 1260.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Queso fundido', 'Porciones 300g', 2082.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Jamón cocido', 'Empaque 250g', 2999.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Salchicha', 'Pack de 6 unidades', 2018.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Yogurt', 'Botella 500ml', 739.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Mantequilla', '250g', 2199.45);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Helado', 'Barril 1 litro', 3210.90);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Frutas deshidratadas', 'Mix 200g', 1934.10);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Semillas mixtas', 'Paquete 200g', 1766.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Almendra', 'Paquete 100g', 2952.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Galletitas dulces', 'Pack 12 unidades', 1659.90);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Paleta', 'Bolsa 20 unidades', 1591.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Caramelos surtidos', 'Bolsa 200g', 2433.20);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Chocolate barra', 'Barra 100g', 1099.80);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Rosquillas', 'Bolsa 10 unidades', 1235.25);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Cereal snack', 'Barra individual', 639.54);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Tostadas de maíz', 'Bolsa 150g', 1212.90);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Salsa de tomate', 'Botella 300ml', 614.90);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Mayonesa', 'Botella 300ml', 840.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Vinagre', 'Botella 350ml', 698.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Mostaza', 'Botella 250ml', 940.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Aceitunas verdes', 'Frasco 200g', 1658.65);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Encurtidos', 'Frasco 500g', 1397.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Chiles en vinagre', 'Lata 200g', 975.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Sopa instantánea', 'Paquete individual', 625.10);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Puré de papa', 'Paquete 125g', 1616.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Conserva de atún', 'Lata 120g', 939.60);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Conserva de melocotón', 'Lata 400g', 2332.50);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Lentejas', 'Paquete 500g', 683.80);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Garbanzos', 'Caja 400g', 891.00);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Alubias', 'Caja 400g', 1181.70);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Té verde', '20 sobres', 1886.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Café instantáneo', 'Frasco 200g', 3222.40);
INSERT INTO mercancia (nombre, descripcion, precio) VALUES  ('Agua tónica', 'Botella 1 litro', 1269.60);

-- Generar operaciones de compra-venta (operacion)
-- Generar 10,000 registros aleatorios
-- Usar DBMS_RANDOM para generar datos aleatorios
-- Fecha entre 2018-01-01 y 2024-09-30
-- id_mercancia entre 1 y 100
-- id_individuo entre 1 y 20
-- id_dependiente entre 1 y 10
-- id_establecimiento entre 1 y 5
-- id_via_pago entre 1 y 3
-- cantidad entre 1 y 5
-- total entre 2.00 y 50.00

BEGIN
  FOR i IN 1..10000 LOOP
    INSERT INTO operacion (
      fecha, id_mercancia, id_individuo, id_dependiente, id_establecimiento, id_via_pago, cantidad, total
    ) VALUES (
      TO_DATE('2018-01-01', 'YYYY-MM-DD') + TRUNC(DBMS_RANDOM.VALUE(0,2450)),
      TRUNC(DBMS_RANDOM.VALUE(1,101)),
      TRUNC(DBMS_RANDOM.VALUE(1,21)),
      TRUNC(DBMS_RANDOM.VALUE(1,11)),
      TRUNC(DBMS_RANDOM.VALUE(1,6)),
      TRUNC(DBMS_RANDOM.VALUE(1,4)),
      TRUNC(DBMS_RANDOM.VALUE(1,6)),
      ROUND(DBMS_RANDOM.VALUE(2,52),2)
    );
  END LOOP;
END;